id: P04170393
initial_creation_type: ocr
source_metadata:
  volumes:
    725dbad5682847e2a474290781c01b1c:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རང་བཞིན་གསུམ་ལ་འཇུག་པའི་སྒྲུབ་པ།
      total_pages: 1605
      volume_number: 57
